# Generated by Django 3.2.8 on 2021-10-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='supply',
            field=models.PositiveIntegerField(default=10000000),
        ),
    ]
