name: Homework 04 - 01 Alexander Jordanov

on:
  push:
    branches: [main, 01_alexander_yordanov_hw_04]
    paths:
      - homework_04/01_Alexander_Yordanov/**
  pull_request:
    branches: [main, 01_alexander_yordanov_hw_04]
    paths:
      - homework_04/01_Alexander_Yordanov/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version : ["3.7", "3.9", "3.10"]
    steps:
      - uses: action/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
          
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Changing Directory
        run: cd homework_04/01_Alexander_Yordanov

      - name: Run pytest
        run: pytest

      - name: Run pylint
        run: pylint *.py 
