name: Homework04 13 Martin Georgiev

on:
  push:
    branches: [ main ]
    paths: 
      - homework_04/13_martin_georgiev/**
  pull_request:
    branches: [ main ]
    paths: 
      - homework_04/13_martin_georgiev/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pylint check
      run: |
        cd homework_04
        cd 13_martin_georgiev
        pylint circles_hw.py
    - name: Pytests
      run: |
        cd homework_04
        cd 13_martin_georgiev
        pytest 
