# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
    paths: 
      - homework_04/10_ivan_enchev/**
  pull_request:
    branches: [ main ]
    paths: 
      - homework_04/10_ivan_enchev/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        cd homework_04
        cd 10_ivan_enchev
        pytest
        
    - name: Pylint check
      run: |
        cd homework_04
        cd 10_ivan_enchev
        pylint main.py
        pylint test_main.py
